apiVersion: apps/v1
kind: Deployment
metadata:
    name: kubernetes-test-service-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kubernetes-test-service
  template:
    metadata:
      labels:
        app: kubernetes-test-service
    spec:
      containers:
        - name: kubernetes-test-service
          image: kubernetes-test-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080

